Document: mediasynclite
Title: Debian mediasynclite Manual
Author: <insert document author here>
Abstract: This manual describes what mediasynclite is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mediasynclite/mediasynclite.sgml.gz

Format: postscript
Files: /usr/share/doc/mediasynclite/mediasynclite.ps.gz

Format: text
Files: /usr/share/doc/mediasynclite/mediasynclite.text.gz

Format: HTML
Index: /usr/share/doc/mediasynclite/html/index.html
Files: /usr/share/doc/mediasynclite/html/*.html
